---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: nodered/node-red
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
          - mountPath: /config
            name: node-red-data
            subPath: config
          imagePullPolicy: IfNotPresent
      volumes:
      - name: node-red-data
        persistentVolumeClaim:
          claimName: node-red-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-pvc
  namespace: default
  labels:
    app: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: node-red-service
  labels:
    app: node-red
spec:
  ports:
  - port: 80
    targetPort: 1880
    name: http
  selector:
    app: node-red
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-red-ingress
  labels:
    app: node-red
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: node-red.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: node-red-service
          servicePort: http