---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer-deployment
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer:latest
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              cpu: 15m
              memory: 105M
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: www/assets/config.yml
              name: homer-config
              subPath: config.yml
            - mountPath: www/assets/icons
              name: homer-data
              subPath: www/assets/icons
          imagePullPolicy: IfNotPresent
      volumes:
      - name: homer-config
        configMap:
          name: homer-config
          items:
            - key: config.yml
              path: config.yml
      - name: homer-data
        persistentVolumeClaim:
          claimName: homer-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc
  namespace: default
  labels:
    app: homer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: homer-service
  labels:
    app: homer
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: homer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homer-ingress
  labels:
    app: homer
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - 'internal.lazz.tech'
  rules:
  - host: internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: homer-service
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  labels:
    app: homer
data:
  config.yml: |
    # See https://fontawesome.com/icons for icons options

    # Optional: Use external configuration file. 
    # Using this will ignore remaining config in this file
    # externalConfig: https://example.com/server-luci/config.yaml

    title: "App dashboard"
    subtitle: "Lazztech"
    # documentTitle: "Welcome" # Customize the browser tab text
    logo: "https://lazz.tech/favicon.png"
    # Alternatively a fa icon can be provided:
    # icon: "fas fa-skull-crossbones"

    header: true # Set to false to hide the header
    footer: false # '<p>Created with <span class="has-text-danger">❤</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

    columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
    connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

    # Optional theming
    theme: default # 'default' or one of the theme available in 'src/assets/themes'.

    # Optional custom stylesheet
    # Will load custom CSS files. Especially useful for custom icon sets.
    # stylesheet:
    #   - "assets/custom.css"

    # Here is the exaustive list of customization parameters
    # However all value are optional and will fallback to default if not set.
    # if you want to change only some of the colors, feel free to remove all unused key.
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: rgb(0 0 0 / 70%)
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
        background-image: "assets/your/light/bg.png"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"
        background-image: "assets/your/dark/bg.png"

    # Optional message
    message:
      # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
      style: "is-warning"
      title: "Work in Progress!"
      content: "Services are largely stable at this point, though a solid backup process is not in place yet. So don't upload any critical data."

    # Optional navbar
    # links: [] # Allows for navbar (dark mode, layout, and search) without any links
    links:
      - name: "Lazztech Status"
        icon: "fas fa-heartbeat"
        url: "https://status.lazz.tech/"
        target: "_blank" # optional html tag target attribute
      - name: "Lazztech Blog"
        icon: "fas fa-blog"
        url: "https://lazz.tech/"
        target: "_blank" # optional html tag target attribute
      - name: "Infrastructure Repo"
        icon: "fab fa-github"
        url: "https://github.com/lazztech/Lazztech.Infrastructure"
        target: "_blank" # optional html tag target attribute
      - name: "Infrastructure Docs"
        icon: "fas fa-book-dead"
        url: "https://lazztech-infrastructure.netlify.app/"
        target: "_blank" # optional html tag target attribute

    # Services
    # First level array represent a group.
    # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
    services:
      - name: "Home & Media"
        icon: "fas fa-building"
        items:
          - name: "Home Assistant"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/home-assistant.png"
            subtitle: "Home Automation"
            tag: "community"
            url: "http://homeassistant.local:8123/"
          # - name: "Plex"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/plex.png"
          #   subtitle: "Media server"
          #   tag: "community"
          #   url: "http://homeassistant.local:32400/web"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Jellyfin"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/jellyfin.png"
            subtitle: "Media server"
            tag: "community"
            url: "https://jellyfin.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "MakeMKV"
            logo: "https://camo.githubusercontent.com/389390a345c649d2efb99c803a3ea9e354567fb4f8ef8085e5834c6299f9b899/68747470733a2f2f696d616765732e7765736572762e6e6c2f3f75726c3d7261772e67697468756275736572636f6e74656e742e636f6d2f6a6c65736167652f646f636b65722d74656d706c617465732f6d61737465722f6a6c65736167652f696d616765732f6d616b656d6b762d69636f6e2e706e6726773d323030"
            subtitle: "Disk ripper"
            tag: "community"
            url: "http://homeassistant.local:8123/hassio/ingress/local_makemkv"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Calibreweb"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/calibreweb.png"
          #   subtitle: "Community Ebook Libary & Reader"
          #   tag: "community"
          #   url: "https://read.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "QuakeJS"
          #   logo: "assets/icons/quakejs.png"
          #   subtitle: "WASM Quake3 in the browser"
          #   tag: "community"
          #   url: "https://quake.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Node Red"
          #   logo: "assets/icons/nodered.png"
          #   subtitle: "Event Automations"
          #   tag: "community"
          #   url: "https://node-red.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Frigate"
          #   logo: "assets/icons/frigate.svg"
          #   subtitle: "Security camera object detection"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://frigate.internal.lazz.tech/"
          # - name: "Double Take"
          #   icon: "fas fa-user-tag"
          #   subtitle: "Facial recognition"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://double-take.internal.lazz.tech/"

      - name: "Productivity"
        icon: "fas fa-building"
        items:
          - name: "Nextcloud"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/nextcloud.png"
            subtitle: "Files, Chat, Productivity & Collaboration"
            tag: "community"
            url: "https://nextcloud.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Wiki"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/wikijs.png"
            subtitle: "Community Wiki"
            tag: "community"
            url: "https://wiki.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Element"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/element.png"
            subtitle: "Matrix chat server"
            tag: "community"
            url: "https://chat.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Paperless-NGX"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/paperless-ng.png"
            subtitle: "Paper document repository"
            tag: "community"
            url: "https://paperless.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Snapdrop"
          #   logo: "assets/icons/snapdrop.png"
          #   subtitle: "The easiest way to transfer data across devices"
          #   tag: "community"
          #   url: "https://share.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet

      - name: "Lazztech"
        icon: "fas fa-code"
        items:
          - name: "Lazz.tech Ghost"
            logo: "https://ghost.org/images/logos/ghost-logo-orb.png"
            subtitle: "Ghost blog CMS"
            tag: "community"
            url: "https://lazz.tech/ghost"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "leolazz.tech"
            logo: "https://lazz.tech/favicon.png"
            subtitle: "Local development deployment"
            tag: "community"
            url: "https://leolazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "dev-lazztechhub-service"
            logo: "https://lazz.tech/favicon.png"
            subtitle: "Local development deployment"
            tag: "community"
            url: "https://dev-lazztechhub.lazz.tech/graphql"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet

      - name: "Development Resources"
        icon: "fas fa-code"
        items:
          - name: "Kubernetes"
            logo: "https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png"
            subtitle: "Kubernetes Dashboard"
            tag: "community"
            url: "https://kubernetes.internal.lazz.tech/"
          # - name: "Gitea"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/gitea.png"
          #   subtitle: "Git repository server"
          #   tag: "community"
          #   url: "https://git.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Drone"
          #   logo: "assets/icons/drone.png"
          #   subtitle: "Container native Continous Integration /Continous Delivery"
          #   tag: "community"
          #   url: "https://cicd.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Jenkins"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/jenkins.png"
          #   subtitle: "CI-CD"
          #   tag: "community"
          #   url: "https://jenkins.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Docker Registry"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/docker.png"
            subtitle: "minimal registry:2 frontend"
            tag: "community"
            url: "https://docker.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Minio"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/minio.png"
            subtitle: "Object file storage"
            tag: "community"
            url: "https://objects.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Code Server"
          #   logo: "assets/icons/code.png"
          #   subtitle: "VSCode web server"
          #   tag: "community"
          #   url: "https://code.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet

      - name: "Monitoring"
        icon: "fas fa-heartbeat"
        items:
          # - name: "Ackee"
          #   logo: "assets/icons/ackee.png"
          #   subtitle: "Site analytics"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://ackee.internal.lazz.tech/"
          - name: "Uptime Kuma"
            logo: "https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.svg"
            subtitle: "Site analytics"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://status.lazz.tech/"
          - name: "Grafana"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/grafana.png"
            subtitle: "Monitoring & Visibility"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://grafana.internal.lazz.tech/"
          - name: "Prometheus"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/prometheus.png"
            subtitle: "Records real-time metrics"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://prometheus.internal.lazz.tech/"
          # - name: "Scrutiny"
          #   logo: "assets/icons/scrutiny.svg"
          #   subtitle: "Hard Drive S.M.A.R.T Monitoring"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://scrutiny.internal.lazz.tech/"

      - name: "SysAdmin"
        icon: "fa fa-server"
        items:
          - name: "Proxmox"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/proxmox.png"
            subtitle: "Hypervisor"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://192.168.1.11:8006/"
          - name: "Duplicati"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/duplicati.png"
            subtitle: "Backups"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://duplicati.internal.lazz.tech"
          - name: "HP Gen10+ ILO"
            logo: "https://i.redd.it/yb6d5h1dixe41.png"
            subtitle: "HPE Integrated Lights Out KVM"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://ilomxq1140rdz/"
          - name: "HP Gen8 ILO"
            logo: "https://i.redd.it/yb6d5h1dixe41.png"
            subtitle: "HPE Integrated Lights Out KVM"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://ilomx245000lj/"
          - name: "Wireguard"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/wireguard.png"
            subtitle: "Wireguard VPN Management"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://wireguard.internal.lazz.tech/"
          # - name: "FreeIPA"
          #   logo: "assets/icons/freeipa.png"
          #   subtitle: "Identity Management"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://ipa.internal.lazz.tech/"
          # - name: "Keycloak"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/keycloak.png"
          #   subtitle: "SSO Identity Provider"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://keycloak.internal.lazz.tech/"
          - name: "Authentik"
            logo: "https://avatars.githubusercontent.com/u/82976448?s=200&v=4"
            subtitle: "SSO Identity Provider"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://authentik.internal.lazz.tech/"
          - name: "Unifi"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/unifi.png"
            subtitle: "Network Management"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://unifi.ui.com/"
          # - name: "Longhorn"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/longhorn.png"
          #   subtitle: "Storage Management"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://longhorn.internal.lazz.tech"
          # - name: "pgAdmin"
          #   logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/pgadmin.png"
          #   subtitle: "Database Management"
          #   tag: "community"
          #   url: "https://pgadmin.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          # - name: "Adminer"
          #   logo: "assets/icons/adminer.png"
          #   subtitle: "Database Management"
          #   tag: "community"
          #   url: "https://adminer.internal.lazz.tech/"
          #   # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          