---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lazztech-acme-cert
spec:
  secretName: lazztech-acme-crt-secret
  dnsNames:
    - "lazz.tech"
    - "*.lazz.tech"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer