---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-acme-cert
spec:
  secretName: internal-acme-crt-secret
  dnsNames:
    - "internal.lazz.tech"
    - "*.internal.lazz.tech" # Your dev URLs wildcard subdomain
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer