apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: "gianlazzarini@gmail.com" # Your email address (given to Let's Encrypt)
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: cloudflare-cert-manager-acme
    solvers:
    - dns01:
        cloudflare:
          email: "gianlazzarini@gmail.com"
          apiTokenSecretRef:
            name: cloudflare
            key: api-key