---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.7.0-alpine
          env:
            - name: url
              value: https://lazz.tech
            - name: mail__transport
              value: SMTP
            - name: mail__options__service
              value: Mailgun
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: user
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
          - mountPath: /var/lib/ghost/content
            name: ghost-data
            subPath: var/lib/ghost/content
          imagePullPolicy: IfNotPresent
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: default
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
spec:
  ports:
  - port: 80
    targetPort: 2368
    name: tcp
  selector:
    app: ghost
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ghost-ingress
  labels:
    app: ghost
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: blog.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: ghost-service
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ghost-lazztech-ingress
  labels:
    app: ghost
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: lazztech-acme-crt-secret
      hosts:
        - 'lazz.tech'
  rules:
  - host: lazz.tech
    http:
      paths:
      - backend:
          serviceName: ghost-service
          servicePort: 80