---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-06-07T21-40-51Z
          args:
            - "server"
            - "/data"
          env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: admin
                key: username
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin
                key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
          - containerPort: 9000
          volumeMounts:
          - mountPath: /data
            name: minio-data
            subPath: data
          - name: tz-config
            mountPath: /etc/localtime
          imagePullPolicy: IfNotPresent
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Los_Angeles
          type: File
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: default
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: tcp
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
  labels:
    app: minio
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: objects.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: minio-service
          servicePort: 80