---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: admin
                    key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp
  selector:
    app: pgadmin
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pgadmin-ingress
  labels:
    app: pgadmin
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: pgadmin.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: pgadmin-service
          servicePort: 80