---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: default
spec:
   replicas: 3
   image: postgres:14.1
   database:
      size: 200Mi
   backup:
       schedule: "0 */1 * * *"
       pvcName: postgres-backup-pvc
       volumeMount: /var/lib/backup
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: admin
              key: password
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: admin
              key: password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: tcp
  selector:
    app: postgres